### ISSUE TITLE
Ignore node_modules files.

### ISSUE THREAD

**Issue by rodwyn** [swordray/sass-lint-webpack#1]
Hello
Can someone help me?
I'm trying to ignore node_modules files.

`plugins: [
    new SassLintPlugin({
			ignoreFiles: [ path.resolve('/node_modules/'), ]
		})
  ]`

**Comment by swordray** [comment]
```js
new SassLintPlugin({
  options: {
    files: {
      ignore: [ 'node_modules/**/*' ],
    },
  },
})
```
